### PR TITLE
fix: implement custom MergeFn to handle JSON merging

### LINKED ISSUE #32: embedded block gets recorded twice
```hcl
resource "aws_apprunner_service" "example" {
  service_name = "example"

  source_configuration {
    image_repository {
      image_configuration {
        port = "8000"
      }
      image_identifier      = "public.ecr.aws/aws-containers/hello-app-runner:latest"
      image_repository_type = "ECR_PUBLIC"
    }
    auto_deployments_enabled = false
  }

  tags = {
    Name = "example-apprunner-service"
  }
}
```

parsed it comes out to

```json
{
  "aws_apprunner_service": {
    "example": {
      "__tfmeta": {
        "filename": "main.tf",
        "line_start": 1,
        "line_end": 18
      },
      "id": "233bfdbe-87e0-4c68-b1f8-eeed134bfbc2",
      "service_name": "example",
      "source_configuration": [
        {
          "__tfmeta": {
            "filename": "main.tf",
            "line_end": 13,
            "line_start": 4
          },
          "auto_deployments_enabled": false,
          "id": "59b3a77a-7bd7-441a-8052-92e7918c9902"
        },
        {
          "image_repository": [
            {
              "__tfmeta": {
                "filename": "main.tf",
                "line_end": 11,
                "line_start": 5
              },
              "id": "97120d4b-6757-4e22-8bb2-214cb220b8a9",
              "image_identifier": "public.ecr.aws/aws-containers/hello-app-runner:latest",
              "image_repository_type": "ECR_PUBLIC"
            }
          ]
        },
        {
          "image_repository": {
            "image_configuration": [
              {
                "__tfmeta": {
                  "filename": "main.tf",
                  "line_end": 8,
                  "line_start": 6
                },
                "id": "6abfb151-96d9-4027-85fb-9a7707967098",
                "port": "8000"
              }
            ]
          }
        }
      ],
      "tags": {
        "Name": "example-apprunner-service"
      }
    }
  }
}
```
 image_repository.configuration got appended to a sibling block instead of as a child under image_repository block.

### PR DESCRIPTION
**Pull request by wwitzel3**
- Fixes #32

### CODE REVIEW

**Comment by wwitzel3** [comment]
In the process of testing the fix #32 we discovered that it created some odd behavior with respect to previously nested array values.

 I'm currently looking in to how to resolve that and have created a new test case in this branch for the behavior.

**Comment by kapilt** [comment]
per offline discussion we want to retain blocks as arrays, and we'll normalize with tf schema in c7n_left.

File: gotfparse/pkg/converter/converter.go [hunk 1]
```diff
@@ -99,16 +99,9 @@ func (t *terraformConverter) VisitJSON() *gabs.Container {
...
-				Filename:  r.GetFilename(),
-				LineStart: r.GetStartLine(),
-				LineEnd:   r.GetEndLine(),
-			}
-			metaJ, _ := json.Marshal(meta)
-			metaP, _ := gabs.ParseJSON(metaJ)
-			if metaP != nil {
-				obj["__tfmeta"] = metaP
+			meta, err := generateTFMeta(b)
+			if err == nil {
```
Comment (kapilt) [inline gotfparse/pkg/converter/converter.go:103]: this seems odd, we're dropping in a empty tfmeta on err?
